### ISSUE TITLE
Virtuosity doesn't virtualize referenced assemblies

### ISSUE THREAD

**Issue by BenderRR** [Fody/Virtuosity#10]
I'm working on mobile application and my solution has next structure

    Foo.Core
    Foo.Core.UnitTests
    Foo.iOS
    Foo.Droid

All projects has reference to Foo.Core.
I added Virtuosity only to Foo.Core.UnitTests project. But Foo.Core doesn't virtualize. What am I doing wrong?

my FodyWeavers.xml

    <?xml version="1.0" encoding="utf-8"?>
    <Weavers VerifyAssembly="true">
    <Virtuosity>
        <IncludeNamespaces>
            Foo.Core
        </IncludeNamespaces>
    </Virtuosity>
    </Weavers>

Or I should add package to Foo.Core project too? But in this case code on production will be virtualized. I think it's not good.

**Comment by SimonCropp** [comment]
It only virtualizes the project u install it into. Not any of the dependencies

**Comment by BenderRR** [comment]
ok, thx.
do u use Virtuosity on prodaction?

**Comment by SimonCropp** [comment]
That is what it is designed for. And yes I do

**Comment by BenderRR** [comment]
@SimonCropp What do you think, is it possible to use Virtuosity only in test project or only when tests run? I do not want to use Virtuosity in prodaction and I want implement my own solution based on your, but I never worked with Fody and I want to know your thoughts about it.

**Comment by SimonCropp** [comment]
> , is it possible to use Virtuosity only in test project or only when tests run? I do not want to use Virtuosity in production

This is something i explicitly decided to not support in Fody. the reason is you are asking to run tests against an IL modified version that will be different from what you deploy. this is inherently dangerous.

**Comment by BenderRR** [comment]
> this is inherently dangerous

Yes, I agree with you
