### ISSUE TITLE
Logging Severity

### ISSUE THREAD

**Issue by marcoerni** [Fody/Virtuosity#11]
Is it possible to decrease the logging severity for the log message which stating that member were made virtual from severity info to debug, like we have already done within the [EmptyConstructor plugin](https://github.com/Fody/EmptyConstructor/issues/8) ?Currently the Virtuosity weaver is extremely chatty and fills up our build log.

**Comment by marcoerni** [comment]
Hi Simon
Thanks, could you release the new version to NuGet also?

**Comment by SimonCropp** [comment]
try now

**Comment by marcoerni** [comment]
its published now, thanks
