### ISSUE TITLE
Disabling for release build?

### ISSUE THREAD

**Issue by MihaMarkic** [Fody/Virtuosity#13]
How would one disable this weaver (or weavers in general) for different configurations? i.e. I'd use it in Debug while not in Release.

**Comment by SimonCropp** [comment]
why would u use it in debug but not production?

**Comment by MihaMarkic** [comment]
Mostly performance. And possible one wouldn't want to let library methods being overridable.

**Comment by SimonCropp** [comment]
so why virtual in debug?

**Comment by MihaMarkic** [comment]
Mocking (unit tests) purposes.

**Comment by SimonCropp** [comment]
but having your tests only pass in debug mode is a very bad idea. essentially u r not deploying what u have tested

**Comment by MihaMarkic** [comment]
It's a trade off I guess. Basically Release code is same as Debug (except for these virtual methods). Of course, IL might be different but I'm not testing the compiler.
OTOH having every method (or just some) as virtual hurts perfs and opens up your code too much.

**Comment by SimonCropp** [comment]
in my testing "virtual hurts perfs" not in any measurable way

but either way, i am sorry, but i think enabling debug only for virtual in this case is an antipattern
