### ISSUE TITLE
Automatic setter property.

### ISSUE THREAD

**Issue by MichaelBuen** [Fody/Virtuosity#23]
This might not be the best repo I post this request. Can't find where to request a new Fody module though.

This child entity is added to User's Add(new ExternalLogin(this)) method:
```
public class ExternalLogin
{
   protected User User { get; set; }

   internal ExternalLogin(User applicationUser) => this.User = applicationUser;

    public void Something()
    {
       this.User = null; // this compiles. a bad thing
    }

}
```

Using NHibernate and C#'s automatic property, a new Fody module that auto-implements a setter would allow NHibernate to set value on ExternalLogin's User while maintaining ExternalLogin's User property be read-only inside ExternalLogin.

```
public class ExternalLogin
{
    // settable in constructor only. but need to be settable by NHibernate too
    protected User User { get; }

    internal ExternalLogin(User applicationUser) => this.User = applicationUser;

    public void Something()
    {
       this.User = null; // this does not compile. a good thing
    }
}
```

Thanks for these awesome Virtuosity and EmptyConstructor library. It made DDD with NHibernate a lot cleaner.

**Comment by SimonCropp** [comment]
Your best bet is to create your own fody weaver that does this
