### ISSUE TITLE
Virtualize methods or Members of a class of a DLL referenced

### ISSUE THREAD

**Issue by dm-conti** [Fody/Virtuosity#51]
I explain my concrete case. I have a Test Solution ("IntegrationServiceTest") with which I want to test a DLL (IntegrationService.dll).
I want virtualize methods and members of a class MyItem that is  contained into IntegrationService.dll. I want mock the class but I need to rendere virtual its methods or member. This are two test that I wrote:

'
		[TestMethod]
        public void TestMyItem()
        {
            Mock<MyItem> mockGameMatchItem = new Mock<MyItem>();
            mockGameMatchItem.Setup(match => match.Session).Returns("CICCIO");
            Assert.AreEqual(mockGameMatchItem.Object.Session, "CICCIO");
        }

        [TestMethod]
        public void TestMyItem_GetSession()
        {
            Mock<MyItem> mockGameMatchItem = new Mock<MyItem>();
            mockGameMatchItem.Setup(match => match.GetSession()).Returns("CICCIO");
            Assert.AreEqual(mockGameMatchItem.Object.GetSession(), "CICCIO");
        }
'

and this is MyItem class:

'
namespace IntegrationServiceBiz
{
    public class MyItem
    {
        public string Session {get; set;}

        public string GetSession() {
            return Session;
        }
    }
}
'

This test throws exceptions: (System.NotSupportedException: Invalid setup on a non-virtual (overridable in VB) member: match => match.GetSession(), this is a MoQ exception); when MyItem is in the DLL but if I put MyItem into IntegrationServiceTest all work fine (so Virtuosity virtualize methods and members and MoQ can mock class).

I added with NuGet manager the Fody and Virtuosity packages in to my test solution (IntegrationServiceTest).
I also added FodyWeavers.xml in the root directory of IntegrationServiceTest.

'
<?xml version="1.0" encoding="utf-8"?>
<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd" VerifyAssembly="true">
  <Virtuosity/>
</Weavers>
'

Is it currently possible to make virtual methods and members of classes imported via DLL with Virtuosity?

**Comment by SimonCropp** [comment]
> Is it currently possible to make virtual methods and members of classes imported via DLL with Virtuosity?

no this is not possible. Fody only manipulates an assembly during the current projects build. It does not manipulate any referenced assemblies

**Comment by dm-conti** [comment]
So, if I can put on DLL project the FodyWeavers.xml file, Fody and Virtuosity packages; It's possible?
(The DLL build processing is under my control)

**Comment by BrunoJuchli** [comment]
> So, if I can put on DLL project the FodyWeavers.xml file, Fody and Virtuosity packages; It's possible?
> (The DLL build processing is under my control)

Yes, when you add FodyWeavers.xml file, Fody and Virtuosity packages to IntegrationService.

-------

I usually don't need Virtuosity.Fody in test projects, just in productive projects.

**Comment by dm-conti** [comment]
Thaks, effectively, I remove FodyWeavers.xml, Fody and Virtuosity from IntegrationServiceTest. I left the file and packages into DLL. The tests are running. I suppose that the FodyWeavers.xml into ServiceIntergrationTest bothered its.

**Comment by SimonCropp** [comment]
so we can close this one?

**Comment by dm-conti** [comment]
Yes thanks. I can make an example if necessary. A little dummy DLL with
configuration used into solution test.

Il lun 8 apr 2019, 21:30 Simon Cropp <notifications@github.com> ha scritto:

**Comment by SimonCropp** [comment]
@dm-conti sorry i am a little confused. i was under the impression you had found a solution?

**Comment by dm-conti** [comment]
yes, I managed to make the two tests work. I make myself available to make
a small example, to put on git, in which I use MoQ + Fody.Virtuosity.
l giorno lunedì 8 aprile 2019, Simon Cropp <notifications@github.com> ha
scritto:

**Comment by SimonCropp** [comment]
@dm-conti thanks for the offer to create a sample. however doing a sample of one use case would mean we should treat all use cases equally, and also treat samples for them. That is too much effort to maintain long term.

BTW to be using Fody [you should be a patron](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md).
