### ISSUE TITLE
Allow to apply to sealed types to support F# records

### ISSUE THREAD

**Issue by DamianReeves** [Fody/Virtuosity#9]
I was hoping to use Virtuosity to change my F# record types to have virtual properties for use with EF 6, but F# record types are sealed.

 - Can this be expanded to allow virtual on sealed types
 - Thinking about this as I'm typing that probably doesn't make sense. What we really need is an Unseal.Fody AddIn to unseal selective types.
 - Any thoughts?

**Comment by SimonCropp** [comment]
does this break some underlying assumptions of how f# works?

**Comment by DamianReeves** [comment]
I don't think it does, but I'm no expert.

**Comment by DamianReeves** [comment]
This stackoverflow chain seems to imply it doesn't:
http://stackoverflow.com/a/26776221/203499

**Comment by SimonCropp** [comment]
Ok then. Then perhaps enable this as a config option?  Want to do a PR?

**Comment by DamianReeves** [comment]
Sure. I can give it a shot. Though it seems like 
Any ideas of what the config options should look like?

How's?

`<Virtuosity UnsealNamespaces="Foo|Bar"/>`


    <Virtuosity>
      <UnsealNamespaces>
           Foo
           Bar
      </UnsealNamespaces>
    </Virtuosity>

Should this really be its own Fody AddIn? I'll gladly do this here (since it means not having to go through setting up a new Addin).

**Comment by SimonCropp** [comment]
ok i think this should be its own addin

**Comment by DamianReeves** [comment]
Unsealed.Fody has been created.
